import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Layout from './component/Layout';
import Modal from './component/Modal';
import Card from './component/Card';
import Accordian from './component/Accordian';
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div>
          <div
            className="hero-section d-flex align-items-center justify-content-center flex-column gap-3"
            style={{
              backgroundImage:
                'url("https://t4.ftcdn.net/jpg/05/72/82/85/360_F_572828530_ofzCYowQVnlOwkcoBJnZqT36klbJzWdn.jpg")',
              backgroundSize: 'cover', // This ensures the image covers the entire div
              backgroundPosition: 'center', // This centers the background image
            }}
          >
            <h1>Welcome to my website</h1>
            <Modal />
          </div>

          <div>
            <h2 className="text-center mt-4">About me</h2>
            <Card />
          </div>
          <div className="accordian my-5">
            <h2 className="text-center">FAQ</h2>
            <Accordian />
          </div>
        </div>
      </Layout>
    </>
  );
}
